<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Label="packaging">
        <IsPackable>true</IsPackable>
        <PackageId>PolyStore</PackageId>
        <Authors>BitCobblers</Authors>
        <Description>Next generation hybrid storage system.</Description>
        <RepositoryUrl>https://github.com/bitcobblers/polystore</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <PropertyGroup Label="building">
        <Optimize Condition="'$(Configuration)' == 'Release'">true</Optimize>
    </PropertyGroup>
</Project>
